enum DataRunTypes { DISTANCE, CALORIESBURNED, AVGSPEED, DURATION }

enum DataAnalysisTypes { DAY, MONTH }

enum OptionTimer { HOUR, MINUTE, SECOND, MILLISECOND }

enum SortType { DATE, RUNNING_TIME, CALORIES_BURNED, DISTANCE, AVG_SPEED }
